# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3349d0a546a24ed752c261942229e2f6dd4ac1d045518884958116cf3ef840cdc422562aaa7efd625eddbd7e16f795fb1af5edfc67ad8ddf47a692f453c7725a

test:
  secret_key_base: 23276e70791e3eb10094886f261f5238379583008698ab02efcfcf919aeaafcb131ff02d7085555a634ebe2f78b7c005dbfe565635d0025ae8cd2d9549d8946c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
